# Generated by Django 3.2.6 on 2021-08-22 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('creating_liquidation', models.TextField()),
                ('managing', models.TextField()),
                ('financing', models.TextField()),
                ('taxing', models.TextField()),
                ('others', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LawsNKO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=100)),
                ('current_laws', models.CharField(max_length=100)),
                ('legal_projects', models.CharField(max_length=100)),
                ('international_docs', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NKOLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LegalProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=100)),
                ('full_description', models.TextField()),
                ('nko_laws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.lawsnko')),
            ],
        ),
        migrations.CreateModel(
            name='InternationalDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=100)),
                ('full_description', models.TextField()),
                ('nko_laws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.lawsnko')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentLegislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=100)),
                ('full_description', models.TextField()),
                ('nko_laws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.lawsnko')),
            ],
        ),
    ]
