# Generated by Django 3.2.6 on 2021-08-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_currentlegislation_faq_internationaldocuments_lawsnko_legalprojects_nkolibrary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawsnko',
            old_name='current_laws',
            new_name='chapters',
        ),
        migrations.RemoveField(
            model_name='lawsnko',
            name='international_docs',
        ),
        migrations.RemoveField(
            model_name='lawsnko',
            name='legal_projects',
        ),
    ]
