# Generated by Django 3.2.6 on 2021-08-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0004_auto_20210822_1355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InternationalDocuments',
            new_name='LawChapters',
        ),
        migrations.RemoveField(
            model_name='legalprojects',
            name='nko_laws',
        ),
        migrations.AlterModelOptions(
            name='lawchapters',
            options={'verbose_name': 'Разделы законодательств', 'verbose_name_plural': 'Разделы законодательств'},
        ),
        migrations.DeleteModel(
            name='CurrentLegislation',
        ),
        migrations.DeleteModel(
            name='LegalProjects',
        ),
    ]
