# Generated by Django 3.2.6 on 2021-08-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0005_auto_20210822_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenews',
            options={'verbose_name': 'Картинки новости', 'verbose_name_plural': 'Картинки новостей'},
        ),
        migrations.AlterModelOptions(
            name='lawchapters',
            options={'verbose_name': 'Разделы законодательств об НКО', 'verbose_name_plural': 'Разделы законодательств об НКО'},
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='creating_liquidation',
            new_name='creating',
        ),
        migrations.AddField(
            model_name='faq',
            name='creating_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='financing_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='managing_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='others_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='taxing_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
