# Generated by Django 3.2.6 on 2021-08-30 18:46

import distributor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0007_aboutus_imageaboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=distributor.models.upload_to),
        ),
    ]
