# Generated by Django 3.2.6 on 2021-08-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0008_aboutus_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageaboutus',
            old_name='about_us',
            new_name='title',
        ),
    ]
