# Generated by Django 3.2.6 on 2021-08-31 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0009_rename_about_us_imageaboutus_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
    ]
